// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOsFy9bFAA2NNk9WyF-FCTjILerc8b6s',
    appId: '1:465127006652:web:7d1961a36090264daacbb9',
    messagingSenderId: '465127006652',
    projectId: 'scrypt-pdf-scanner',
    authDomain: 'scrypt-pdf-scanner.firebaseapp.com',
    storageBucket: 'scrypt-pdf-scanner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH39BhXeiZDeVpL9CE-SMwoXBp0QofkQk',
    appId: '1:465127006652:android:579176b911d71774aacbb9',
    messagingSenderId: '465127006652',
    projectId: 'scrypt-pdf-scanner',
    storageBucket: 'scrypt-pdf-scanner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4Yp_TWBZ6mSAUPa_zQB_Fn4xzRTZlLA',
    appId: '1:465127006652:ios:0ff4a01c2c6d3a02aacbb9',
    messagingSenderId: '465127006652',
    projectId: 'scrypt-pdf-scanner',
    storageBucket: 'scrypt-pdf-scanner.appspot.com',
    iosClientId: '465127006652-rhqds5v8k9alr6uvr7njahsg9cm17jgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.scansquad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP4Yp_TWBZ6mSAUPa_zQB_Fn4xzRTZlLA',
    appId: '1:465127006652:ios:0ff4a01c2c6d3a02aacbb9',
    messagingSenderId: '465127006652',
    projectId: 'scrypt-pdf-scanner',
    storageBucket: 'scrypt-pdf-scanner.appspot.com',
    iosClientId: '465127006652-rhqds5v8k9alr6uvr7njahsg9cm17jgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.scansquad',
  );
}
